### ISSUE TITLE
after fncs is killed still publishing checking on fncs process for different simulations

### ISSUE THREAD

**Issue by craig8** [GRIDAPPSD/GOSS-GridAPPS-D#997] opened 2019-07-12 02:49 UTC
Note I ran a couple of simulations and then killed off fncs and yet the platform is still publishing about checking if a simulation is still running...
![image](https://user-images.githubusercontent.com/3979063/61098757-ef252180-a414-11e9-8d29-735af96aa270.png)

````
PlatformLog------------------------------------------------------------
MESSAGE
Checking if FNCS simulation is finished, currently false, processid: 1089806251
END ONLOG------------------------------------------------------------
LOG_COUNT: 416

PlatformLog------------------------------------------------------------
MESSAGE
Checking if FNCS simulation is finished, currently false, processid: 1354934572
END ONLOG------------------------------------------------------------
LOG_COUNT: 417
````

**Comment by poorva1209** [comment] 2021-03-01 18:15
The issue is closed by using HELICS.

**Closed by poorva1209** 2021-03-01 18:15 UTC
Labels: multiple-simulation-support
