### ISSUE TITLE
Check and resolve floating switches on Viz

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#1180] opened 2020-01-06 21:05 UTC
Floating switches like these: 

![image](https://user-images.githubusercontent.com/6538501/72101432-84787400-32d9-11ea-925f-9b89fdba34cf.png)

These are taken from this part of the model :+1:  
![image](https://user-images.githubusercontent.com/6538501/72101511-b7bb0300-32d9-11ea-9e2b-63ee722afdeb.png)

But floating switches like these can be found on other parts of the model too. 
We need to figure out why they are not connected like this. Is there a problem in the coordinates or the rendering? 

@temcdrm can help you out if this is data related.

**Comment by nhuyvan** [comment] 2020-01-06 21:10
@poorva1209 Can you provide more description on this?

**Comment by poorva1209** [comment] 2020-01-06 21:41
> @poorva1209 Can you provide more description on this?

Yesh, I will be adding screenshots to this issue later with more details.

**Comment by bibiraju** [comment] 2020-01-14 21:32
@nhuyvan I remember fixing this for smaller model like 13 node. Can we use the same logic to fix 9500 model, maybe the difference is because 9500 model is in lat/long

**Comment by nhuyvan** [comment] 2020-01-17 03:42
A fix was merged into develop. You will still see switches which appear to be missing either the left node or right node, this is caused by the model, I wasn't sure how to proceed in such a case, so I opted to not programmatically introduce the missing nodes

**Comment by temcdrm** [comment] 2020-01-17 15:50
Those could be normally open tie switches to adjacent circuit segments that are not included in the model.  So long as the power flow through those switches is actually zero, the visualization is okay.  Most of those normally open tie switches ought to appear on the boundaries of the displayed model.

**Comment by poorva1209** [comment] 2020-01-21 19:41
@Jon8080 @AAndersn This is ready to be tested. **Please read the discussion above before testing.** Please test the latest develop tag and either close this task or comment here.

**Comment by AAndersn** [comment] 2020-01-21 23:40
s@nhuyvan @poorva1209 , I have tested the develop release and don't see any changes in switch representation. 

I did take a couple screenshots showing the DSS and GridApps-D plots of the same nodes. All of the bus coordinates worked in the DSS files, and you can use that to see how the switches are supposed to connect to their from- and to- nodes

![switches 01](https://user-images.githubusercontent.com/19935503/72852744-851bed80-3c7d-11ea-85cd-42062af8c920.png)

![switches 02](https://user-images.githubusercontent.com/19935503/72852749-89480b00-3c7d-11ea-9cb6-f74d4f84cef8.png)

**Comment by poorva1209** [comment] 2020-01-22 17:42
@nhuyvan @bibiraju Any idea what's happening here? looks like some switches are not connected to anything.

**Comment by nhuyvan** [comment] 2020-01-22 19:55
@poorva1209 That picture doesn't like it has the latest changes, I also checked the 9500 model, I didn't see those switches that aren't connected to anything. 

@bibiraju Can you check the 9500 again?

**Comment by poorva1209** [comment] 2020-01-22 19:57
@AAndersn Can you make sure you have the latest develop version?

**Comment by AAndersn** [comment] 2020-01-23 00:31
I am running the normal launch command 

```
cd gridappsd-docker
./run.sh -t develop
```

I am testing on the PyVVO and WSU-VVO servers (172.20.128.206 and 172.20.128.214).

It could be an issue of containers not updating, or maybe the updated viz isn't fully pushed to the develop branch.

**Comment by AAndersn** [comment] 2020-01-23 00:33
@nhuyvan Perhaps I need to manually update my docker-compose.yml file?

The section for the viz currently reads:

```
viz:
    image: gridappsd/viz:2019.12.0
    ports:
      - 8080:8082

    depends_on:
      - gridappsd

    volumes:
      - /home/d3m614/gridappsd-docker/viz.config:/gridappsd/viz/config.json
```

**Comment by nhuyvan** [comment] 2020-01-23 16:09
@AAndersn Can you try this `image: gridappsd/viz${GRIDAPPSD_TAG}` instead of `image: gridappsd/viz:2019.12.0`

**Comment by AAndersn** [comment] 2020-01-23 20:05
@nhuyvan @poorva1209 Updating the docker-compose file worked.

I think this is good enough for all future demos and evaluation.

![image](https://user-images.githubusercontent.com/19935503/73019470-a7367c80-3df1-11ea-9f56-62502dfe07cd.png)

**Closed** 2020-01-23 21:31 UTC
Labels: bug
