### ISSUE TITLE
Plot selection page not updating when model is changed.

### ISSUE THREAD

**Issue by bibiraju** [GRIDAPPSD/GOSS-GridAPPS-D#1375] opened 2020-10-02 17:37 UTC
Need to try reproducing the issue

**Comment by bibiraju** [comment] 2020-10-02 17:46
@poorva1209 I couldn't reproduce the issue. Please let me know the steps to reproduce the issue

**Comment by poorva1209** [comment] 2020-10-02 17:50
@bibiraju Can I call you Team right now?

**Comment by poorva1209** [comment] 2020-10-02 17:55
@bibiraju I tried again even I can't reproduce it :) 
I will try again and let you know when I can.

**Comment by bibiraju** [comment] 2020-12-08 19:26
@poorva1209 I tried again but could not reproduce the issue.

**Comment by poorva1209** [comment] 2021-01-04 20:04
Resolved. Closing the issue.

**Closed by poorva1209** 2021-01-04 20:04 UTC
Labels: bug, comp-viz
