### ISSUE TITLE
Service providing cluster's disclosure endpoints

### ISSUE THREAD

**Issue by telsethag** [GRIDAPPSD/GOSS-GridAPPS-D#887] opened 2019-04-04 17:48 UTC
### Description of Issue
Provide a service that returns cluster's disclosure endpoints for client usage.  Information is provided for Hazelcast client connections.

**Comment by ericstephan** [comment] 2020-01-07 23:14
@telsethag duplicate of issue 888.

**Closed by ericstephan** 2020-01-07 23:14 UTC
Labels: proven-client, proven-server
