### ISSUE TITLE
Measurements for Substation regulator are missing

### ISSUE THREAD

**Issue by shpoudel** [GRIDAPPSD/GOSS-GridAPPS-D#1597] opened 2022-02-03 20:50 UTC
I noticed this when running the simulation with the IEEE 123-bus feeder. There is a warning displayed at each time step "measurements for reg1a are missing". I am not sure if this is intended or a bug, but this issue will affect the dynamic Ybus and power flow service within the App toolbox.

**Comment by AAndersn** [comment] 2022-02-05 02:07
@shpoudel - I think this is the same issue as #1590 . It actually covers all regulators and split-phase customer secondary transformers.

**Comment by AAndersn** [comment] 2022-02-05 02:13
@shpoudel - also related issue is that this particular regulator is associated with a PowerTransformerEnd, not a TransformerTankEnd. 

It actually broke my topology processor code earlier this morning. If you query for the object dictionary, you will see it is defined differently:

```
{'data': [{'id': '_9DA10945-2EDC-43C9-A748-B079D826B0DB',
   'Equipment.EquipmentContainer': '_C1C3E687-6FFD-C753-582B-632A27E28507',
   'IdentifiedObject.mRID': '_9DA10945-2EDC-43C9-A748-B079D826B0DB',
   'IdentifiedObject.name': 'reg1a',
   'PowerSystemResource.Location': '_DC79114D-74F2-4539-A7BE-882BC46F487B',
   'PowerTransformer.vectorGroup': 'Yy',
   'type': 'PowerTransformer'}],
 'responseComplete': True,
 'id': '1581037956'}
```

**Comment by AAndersn** [comment] 2022-02-08 22:21
Duplicate of #1102

**Comment by shpoudel** [comment] 2022-02-17 22:54
Regulator tap positions telemetry is common and important for a range of algorithms including App toolbox services under active development. While the root cause may be the same as #1102 and #1590,  this is a separate high-priority issue.

**Comment by shpoudel** [comment] 2022-02-17 22:57
@poorva1209 Please decide how best to assign this.

**Comment by shpoudel** [comment] 2022-02-17 23:38
This is something that needs to be changed inside the CIMHub utils "ListMesureables.py" and probably inside "InsertMeasurements.py". If this doesn't solve the problem, then we should look into how the "model_dict.json" is created.

**Comment by shpoudel** [comment] 2022-02-18 01:30
I updated CIMHub utils and it seems like this got fixed. I will test with one more feeder model and will create a pull request.

**Comment by poorva1209** [comment] 2022-07-28 19:11
@shpoudel  Is the pull request ready to merge this?

**Comment by shpoudel** [comment] 2022-07-28 19:30
The pull request for this has already been merged.

**Closed** 2022-07-28 19:55 UTC
Labels: app-critical
