### ISSUE TITLE
fncs and gridlab d not cleaned up after simulation completed

### ISSUE THREAD

**Issue by craig8** [GRIDAPPSD/GOSS-GridAPPS-D#996] opened 2019-07-12 02:44 UTC
Note if there is an explicit stop from the gui that I am not using please let me know.

The following will happen if there is more than one simulation started.  The process manager seems to get confused or something happens...anyhow this is going to lock up a lot of memory after a few runs.

![image](https://user-images.githubusercontent.com/3979063/61098532-33fc8880-a414-11e9-949d-0d2a91bfee79.png)

````
PlatformLog------------------------------------------------------------
MESSAGE
Checking if FNCS simulation is finished, currently false, processid: 1195760034
END ONLOG------------------------------------------------------------
LOG_COUNT: 447

PlatformLog------------------------------------------------------------
MESSAGE
Checking if FNCS simulation is finished, currently false, processid: 1345851081
END ONLOG------------------------------------------------------------
LOG_COUNT: 448

PlatformLog------------------------------------------------------------
MESSAGE
Checking if FNCS simulation is finished, currently false, processid: 2060320263
END ONLOG------------------------------------------------------------
LOG_COUNT: 449

PlatformLog------------------------------------------------------------
MESSAGE
Checking if FNCS simulation is finished, currently false, processid: 1354934572
END ONLOG------------------------------------------------------------
LOG_COUNT: 450

PlatformLog------------------------------------------------------------
MESSAGE
Checking if FNCS simulation is finished, currently false, processid: 1195760034
END ONLOG------------------------------------------------------------
LOG_COUNT: 451

PlatformLog------------------------------------------------------------
MESSAGE
Checking if FNCS simulation is finished, currently false, processid: 1345851081
END ONLOG------------------------------------------------------------
LOG_COUNT: 452

PlatformLog------------------------------------------------------------
MESSAGE
Checking if FNCS simulation is finished, currently false, processid: 2060320263
END ONLOG------------------------------------------------------------
````

**Comment by poorva1209** [comment] 2021-03-01 18:14
The issue is closed by using HELICS.

**Closed by poorva1209** 2021-03-01 18:14 UTC
Labels: multiple-simulation-support
