### ISSUE TITLE
Residential Module in Simulation

### ISSUE THREAD

**Issue by temcdrm** [GRIDAPPSD/GOSS-GridAPPS-D#347] opened 2017-11-16 19:16 UTC
Need a simulator option that includes houses. Rather than put them in the CIM right away, we need a house-generator method that will calibrate to the feeder peak load. This would be an experimental feature.

**Comment by poorva1209** [comment] 2018-06-28 18:15
Duplicate of #589

**Closed by poorva1209** 2018-06-28 18:15 UTC
