### ISSUE TITLE
Sending a command to change set point to the PV inverter has no effect.

### ISSUE THREAD

**Issue by Jeffrey-Simpson** [GRIDAPPSD/GOSS-GridAPPS-D#852] opened 2019-02-19 20:21 UTC
### Description of Issue
Sending a command to change set point to the PV inverter has no effect.

### Command

```
{'command': 'update', 'input': {'simulation_id': 377477281, 'message': {'timestamp': 1550264179, 'difference_mrid': 'be2ba108-7b32-4a2c-9136-baaaff2ced6a', 'reverse_differences': [{'object': '_7C422C31-8289-5D6A-F6EF-65EE298D259C', 'attribute': 'PowerElectronicsConnection.p', 'value': -291130264.213}, {'object': '_7C422C31-8289-5D6A-F6EF-65EE298D259C', 'attribute': 'PowerElectronicsConnection.q', 'value': 180000.0}], 'forward_differences': [{'object': '_7C422C31-8289-5D6A-F6EF-65EE298D259C', 'attribute': 'PowerElectronicsConnection.p', 'value': -0.0}, {'object': '_7C422C31-8289-5D6A-F6EF-65EE298D259C', 'attribute': 'PowerElectronicsConnection.q', 'value': -300000.0}]}}}
```

This message should be going to the inverter for dg_84_PVPanels
```
grep 7C422C31-8289-5D6A-F6EF-65EE298D259C model_dict.json 
{"name":"dg_84_PVPanels","mRID":"_7C422C31-8289-5D6A-F6EF-65EE298D259C","CN1":"104","phases":"C","ratedS":300000.0,"ratedU":2400.0,"p":300000.000,"q":0.000,"maxIFault":1.111}
```

### Distribution Model:
https://spteams1.pnnl.gov/sites/ADMS/Shared%20Documents/ADMS%20Applications/NREL_DER_Dispatch/ieee123_pv_reg_CIM.xml.zip
Note that the measurements have to be added to the model with the Powergrid model scrips.
https://github.com/GRIDAPPSD/Powergrid-Models/tree/master/Meas

### Affected Version
2019.02
#### Expected
See the values of the PV inverter change.
#### Actual
Values are unchanged.

**Comment by afisher1** [comment] 2019-03-14 16:47
I've found the cause for this. cim2glm is creating the inverter object in gridlabd with the generator_mode set to CONSTANT_PQ. It should be corrected to set the four_quadrant_control_mode to CONSTANT_PQ.

**Comment by afisher1** [comment] 2019-03-14 16:47
Closing this issue as it needs to be part of the PowergridModels repo.

**Closed** 2019-03-19 18:07 UTC
Labels: app-critical
